export const SOURCE_CHECKED_LABEL = 'Sources checked September 2026'
export const WHO_OVERVIEW_URL = 'https://www.who.int/news-room/fact-sheets/detail/mental-disorders'
export const CRISIS_SUPPORT_URL = 'https://988lifeline.org/'

export const DISORDERS = [
  {
    id: 'anxiety',
    title: 'Anxiety Disorders',
    color: '#9a6b2a',
    source: 'Mayo Clinic',
    sourceUrl: 'https://www.mayoclinic.org/diseases-conditions/anxiety/symptoms-causes/syc-20350961',
    what: 'Anxiety disorders involve excessive, persistent fear or worry that is difficult to control and significantly interferes with daily activities. They include generalized anxiety disorder, panic disorder, social anxiety disorder, and other related conditions.',
    symptoms: [
      'Feeling nervous, restless, or tense',
      'Excessive worry or fear that is difficult to control',
      'A sense of impending danger, panic, or doom',
      'A rapid heartbeat, sweating, or trembling',
      'Trouble sleeping or concentrating',
    ],
    causes: [
      'Traumatic or stressful life experiences',
      'Family history of anxiety disorders',
      'Certain temperament or personality traits',
      'Other mental or physical health conditions',
    ],
    treatment: [
      'Psychotherapy, including cognitive behavioral therapy (CBT)',
      'Medication when recommended by a qualified clinician',
      'Supportive routines such as physical activity, sleep care, and social connection',
    ],
  },
  {
    id: 'depression',
    title: 'Depression',
    color: '#3a6898',
    source: 'Mayo Clinic',
    sourceUrl: 'https://www.mayoclinic.org/diseases-conditions/depression/symptoms-causes/syc-20356007',
    what: 'Depression is a common and serious mood disorder that can cause persistent sadness, irritability, emptiness, or loss of interest. It can affect thoughts, feelings, sleep, appetite, concentration, and daily functioning.',
    symptoms: [
      'Persistent sadness, emptiness, irritability, or hopelessness',
      'Loss of interest or pleasure in activities once enjoyed',
      'Fatigue or lack of energy',
      'Changes in sleep or appetite',
      'Difficulty thinking, concentrating, or making decisions',
    ],
    causes: [
      'A combination of biological, psychological, and social factors',
      'Family history or inherited vulnerability',
      'Some medical conditions or hormonal changes',
      'Trauma, loss, prolonged stress, or limited social support',
    ],
    treatment: [
      'Psychotherapy, including cognitive behavioral therapy (CBT)',
      'Antidepressant medication when clinically appropriate',
      'A combination of therapy, medication, and supportive routines for some people',
      'Care for related medical or mental health conditions',
    ],
  },
  {
    id: 'bipolar',
    title: 'Bipolar Disorder',
    color: '#735d8f',
    source: 'Mayo Clinic',
    sourceUrl: 'https://www.mayoclinic.org/diseases-conditions/bipolar-disorder/symptoms-causes/syc-20355955',
    what: 'Bipolar disorder causes episodes of unusually elevated or irritable mood and energy, called mania or hypomania, as well as depressive episodes. These episodes can affect sleep, activity, judgment, behavior, and the ability to think clearly.',
    symptoms: [
      'Manic or hypomanic episodes with increased energy or activity',
      'A reduced need for sleep during elevated mood episodes',
      'Unusually fast speech, racing thoughts, or impulsive decisions',
      'Depressive episodes with low mood or loss of interest',
      'Changes in concentration, motivation, and daily functioning',
    ],
    causes: [
      'The exact cause is not known',
      'Genetic factors can increase vulnerability',
      'Differences in brain structure or function may contribute',
      'Stress and sleep disruption can affect episodes in some people',
    ],
    treatment: [
      'Mood-stabilizing or other psychiatric medication prescribed by a clinician',
      'Psychotherapy and education about mood patterns',
      'Consistent sleep, routine, and stress management',
      'Ongoing follow-up because treatment needs can change over time',
    ],
  },
  {
    id: 'ptsd',
    title: 'Post-Traumatic Stress Disorder (PTSD)',
    color: '#b96535',
    source: 'Mayo Clinic',
    sourceUrl: 'https://www.mayoclinic.org/diseases-conditions/post-traumatic-stress-disorder/symptoms-causes/syc-20355967',
    what: 'PTSD can develop after experiencing or witnessing a traumatic event. Many people have temporary stress responses after trauma. PTSD involves symptoms that persist, cause distress, and interfere with daily life.',
    symptoms: [
      'Intrusive memories, flashbacks, or nightmares',
      'Avoidance of reminders connected with the trauma',
      'Negative changes in thoughts, mood, or emotional connection',
      'Feeling easily startled, constantly on guard, or unable to sleep',
    ],
    causes: [
      'Exposure to an extremely threatening or traumatic event',
      'Severe, repeated, or prolonged trauma can increase risk',
      'Previous trauma or other mental health conditions may increase vulnerability',
      'Social support and personal circumstances can affect recovery',
    ],
    treatment: [
      'Trauma-focused psychotherapy from a qualified professional',
      'Medication when clinically appropriate',
      'Support from trusted people, peer groups, or care teams',
    ],
  },
  {
    id: 'schizophrenia',
    title: 'Schizophrenia',
    color: '#a54f4f',
    source: 'Mayo Clinic',
    sourceUrl: 'https://www.mayoclinic.org/diseases-conditions/schizophrenia/symptoms-causes/syc-20354443',
    what: 'Schizophrenia is a serious mental health condition that can affect perception, thought, speech, behavior, and daily functioning. Experiences vary by person and may include hallucinations, delusions, disorganized thinking, or reduced motivation and emotional expression.',
    symptoms: [
      'Delusions, or strongly held beliefs that are not based in reality',
      'Hallucinations, such as hearing or seeing things others do not',
      'Disorganized thinking or speech',
      'Reduced emotional expression or social connection',
      'Loss of motivation or difficulty with daily activities',
    ],
    causes: [
      'The exact cause is not known',
      'Family history can increase vulnerability',
      'Differences in brain chemistry or development may contribute',
      'Environmental factors can interact with biological vulnerability',
    ],
    treatment: [
      'Antipsychotic medication prescribed and monitored by a clinician',
      'Psychotherapy and education about the condition',
      'Support for relationships, school, work, and daily living',
      'Coordinated care involving the person, clinicians, and trusted supporters',
    ],
  },
  {
    id: 'eating',
    title: 'Eating Disorders',
    color: '#a85f78',
    source: 'Mayo Clinic',
    sourceUrl: 'https://www.mayoclinic.org/diseases-conditions/eating-disorders/symptoms-causes/syc-20353603',
    what: 'Eating disorders are serious mental health conditions involving persistent eating behaviors and related thoughts or emotions that harm physical health or daily functioning. They can affect people of any body size or background.',
    symptoms: [
      'Persistent preoccupation with food, weight, body shape, or eating',
      'Restrictive eating, binge eating, purging, or other compensatory behavior',
      'Distress around meals or eating with other people',
      'Changes in physical health, energy, or concentration',
      'Withdrawal from routines or relationships',
    ],
    causes: [
      'A combination of genetic, psychological, and social factors',
      'Anxiety, depression, perfectionism, or other vulnerabilities',
      'Social and cultural pressure related to appearance or weight',
      'Dieting, weight stigma, bullying, or stressful experiences',
    ],
    treatment: [
      'Psychotherapy tailored to the person and type of eating disorder',
      'Nutrition support from a qualified professional',
      'Medical monitoring for physical complications',
      'Medication for some symptoms or conditions when clinically appropriate',
    ],
  },
  {
    id: 'odd',
    title: 'Oppositional Defiant Disorder (ODD)',
    color: '#4d6b58',
    source: 'Mayo Clinic',
    sourceUrl: 'https://www.mayoclinic.org/diseases-conditions/oppositional-defiant-disorder/symptoms-causes/syc-20375831',
    what: 'Oppositional defiant disorder is diagnosed in children and adolescents who show a frequent, ongoing pattern of angry or irritable mood, argumentative or defiant behavior, or vindictiveness that causes significant problems in daily life.',
    symptoms: [
      'Frequently losing their temper or becoming easily annoyed',
      'Often arguing with adults or people in authority',
      'Regularly refusing age-appropriate requests or rules',
      'Blaming others for mistakes or behavior',
      'Spiteful or vindictive behavior',
    ],
    causes: [
      'There is no single known cause',
      'Temperament and emotional regulation can play a role',
      'Genetic, developmental, family, and environmental factors may interact',
      'A qualified professional considers the child, family, school, and broader context',
    ],
    treatment: [
      'Parent or caregiver training that builds consistent, positive strategies',
      'Family therapy to support communication and relationships',
      'Individual support for problem-solving and emotional regulation',
      'Care for co-occurring conditions such as ADHD or anxiety',
    ],
  },
  {
    id: 'neuro',
    title: 'Neurodevelopmental Disorders',
    color: '#3f7773',
    source: 'World Health Organization',
    sourceUrl: WHO_OVERVIEW_URL,
    what: 'Neurodevelopmental disorders begin during the developmental period and affect the acquisition or use of intellectual, motor, language, attention, or social skills. This broad group includes ADHD, autism spectrum disorder, intellectual developmental disorders, and other conditions.',
    symptoms: [
      'Differences in attention, activity, impulse control, or executive functioning',
      'Differences in communication or social interaction',
      'Delays or challenges involving language, movement, or learning',
      'Repetitive patterns of behavior or highly focused interests for some people',
      'Support needs that vary across people, settings, and life stages',
    ],
    causes: [
      'There is no single cause across this broad group',
      'Genetic and developmental factors can contribute',
      'Some prenatal, birth, medical, or environmental factors can affect development',
      'Causes and support needs differ by condition and person',
    ],
    treatment: [
      'Early and ongoing support based on individual strengths and needs',
      'Educational accommodations and learning support',
      'Speech, occupational, behavioral, or other therapies when helpful',
      'Medication for specific symptoms when clinically appropriate',
    ],
  },
]

export const DISORDER_LABELS = Object.fromEntries(DISORDERS.map((item) => [item.id, item.title]))

export const QUIZ_BANK = {
  anxiety: [
    ['What most clearly distinguishes an anxiety disorder from ordinary, temporary anxiety?', ['It is persistent, difficult to control, and interferes with daily life', 'It always begins after one identifiable stressful event', 'It always includes a panic attack', 'It requires medication to improve'], 'It is persistent, difficult to control, and interferes with daily life', 'Intensity, persistence, and interference with everyday functioning help distinguish an anxiety disorder from ordinary anxiety.'],
    ['How can cognitive behavioral therapy help with anxiety?', ['It helps people notice and respond differently to unhelpful thoughts and behaviors', 'It prevents every future experience of anxiety', 'It relies only on avoiding anxiety-provoking situations', 'It works by replacing sleep and physical activity'], 'It helps people notice and respond differently to unhelpful thoughts and behaviors', 'CBT builds practical skills for understanding thoughts, emotions, and behaviors. It does not promise to remove every anxious feeling.'],
    ['Which description best fits a panic attack?', ['A sudden surge of intense fear or discomfort with physical symptoms', 'A low mood that develops gradually over several weeks', 'A constant preference for being alone', 'A brief period of ordinary nervousness before a test'], 'A sudden surge of intense fear or discomfort with physical symptoms', 'Panic attacks are sudden episodes of intense fear or discomfort that can include a racing heart, shortness of breath, or dizziness.'],
    ['What does a risk factor for an anxiety disorder mean?', ['It may increase vulnerability but does not guarantee a disorder', 'It confirms that a person has an anxiety disorder', 'It identifies the single cause of every anxiety disorder', 'It determines which treatment will work'], 'It may increase vulnerability but does not guarantee a disorder', 'Risk factors can raise vulnerability, but anxiety disorders usually reflect several interacting factors rather than one certain cause.'],
  ],
  depression: [
    ['What most clearly distinguishes depression from a short period of sadness?', ['Symptoms persist and affect everyday functioning', 'Sadness is present after a difficult event', 'A person wants time alone for a day', 'Mood improves after rest'], 'Symptoms persist and affect everyday functioning', 'Depression involves persistent symptoms that affect areas such as interest, sleep, concentration, relationships, or daily responsibilities.'],
    ['What does loss of interest or pleasure refer to in depression?', ['Activities that once felt meaningful or enjoyable no longer do', 'A person changes one hobby for another', 'A person needs quiet time after a busy day', 'A person dislikes a task they have never enjoyed'], 'Activities that once felt meaningful or enjoyable no longer do', 'A reduced ability to feel interest or pleasure is a common feature of depression and can affect many parts of life.'],
    ['Which statement best describes treatment for depression?', ['Treatment is individualized and may include therapy, medication, or both', 'The same treatment plan works for everyone', 'Medication is the only evidence-based option', 'Treatment should wait until symptoms become severe'], 'Treatment is individualized and may include therapy, medication, or both', 'Depression treatment is tailored to the person and may combine psychotherapy, medication, health care, and supportive routines.'],
    ['Why can depression affect concentration and decision-making?', ['It can change energy, sleep, motivation, and patterns of thinking', 'It permanently lowers intelligence', 'It affects concentration only when medication is used', 'It prevents a person from learning new information'], 'It can change energy, sleep, motivation, and patterns of thinking', 'Depression can affect several connected systems, including sleep, energy, attention, motivation, and thinking.'],
  ],
  bipolar: [
    ['Which description best reflects bipolar disorder?', ['Distinct mood episodes that can include mania or hypomania and depression', 'Ordinary mood changes that happen within a single day', 'Persistent anxiety without changes in energy or activity', 'One depressive episode with no history of elevated mood'], 'Distinct mood episodes that can include mania or hypomania and depression', 'Bipolar disorders involve distinct episodes of elevated or irritable mood and energy, often alongside depressive episodes.'],
    ['How is mania different from simply feeling energetic or productive?', ['It is a marked change in mood and activity that can impair judgment or functioning', 'It always feels pleasant to the person experiencing it', 'It lasts only as long as a productive afternoon', 'It is defined only by sleeping one hour less than usual'], 'It is a marked change in mood and activity that can impair judgment or functioning', 'Mania is more than high energy. It is a significant episode that can affect sleep, judgment, behavior, relationships, and safety.'],
    ['Why is an ongoing treatment plan important for bipolar disorder?', ['Symptoms and treatment needs can change across mood episodes and over time', 'Treatment removes every future mood change', 'Care is useful only during depressive episodes', 'Routines can replace professional treatment'], 'Symptoms and treatment needs can change across mood episodes and over time', 'Ongoing care helps monitor changing symptoms, treatment response, sleep, and risks across different mood states.'],
    ['What is one useful purpose of tracking sleep and mood patterns?', ['It can help a person and care team notice meaningful changes over time', 'It can confirm a diagnosis without professional evaluation', 'It can predict every mood episode in advance', 'It can replace medication or psychotherapy'], 'It can help a person and care team notice meaningful changes over time', 'Tracking can reveal patterns and support conversations with a care team, but it is not a diagnostic tool or a replacement for treatment.'],
  ],
  ptsd: [
    ['Which statement best describes the relationship between trauma and PTSD?', ['PTSD can develop when trauma responses persist and interfere with daily life', 'Everyone who experiences trauma develops PTSD', 'PTSD begins only immediately after an event', 'Trauma affects memory but not mood or behavior'], 'PTSD can develop when trauma responses persist and interfere with daily life', 'Many people have temporary responses after trauma. PTSD involves a pattern of symptoms that persists and causes significant distress or impairment.'],
    ['What does avoidance mean in the context of PTSD?', ['Trying to stay away from thoughts, feelings, people, or places linked to the trauma', 'Taking healthy breaks from stressful work', 'Choosing not to discuss unrelated private information', 'Having difficulty remembering an ordinary appointment'], 'Trying to stay away from thoughts, feelings, people, or places linked to the trauma', 'Avoidance can reduce distress briefly while making it harder to process the trauma or return to important parts of life.'],
    ['Which group contains recognized PTSD symptom areas?', ['Intrusion, avoidance, changes in mood or thinking, and heightened threat response', 'Elevated mood, increased appetite, and improved concentration', 'Language delay, restricted interests, and impulsivity', 'Persistent defiance, vindictiveness, and rule refusal'], 'Intrusion, avoidance, changes in mood or thinking, and heightened threat response', 'PTSD can involve re-experiencing, avoidance, negative changes in mood or thought, and feeling persistently on guard.'],
    ['Which care approach has evidence for treating PTSD?', ['Trauma-focused psychotherapy delivered by a qualified professional', 'Avoiding every reminder indefinitely', 'Discussing the trauma before the person feels safe enough to participate', 'Using physical activity as the only treatment'], 'Trauma-focused psychotherapy delivered by a qualified professional', 'Evidence-based trauma-focused therapies can help people process trauma safely. Treatment should be individualized and collaborative.'],
  ],
  schizophrenia: [
    ['What is a hallucination?', ['A sensory experience that feels real but is not shared by others', 'A strongly held belief that conflicts with available evidence', 'A temporary problem remembering a name', 'A rapid change from sadness to happiness'], 'A sensory experience that feels real but is not shared by others', 'Hallucinations involve hearing, seeing, or otherwise sensing something that is not present for other people.'],
    ['What is the difference between a delusion and a hallucination?', ['A delusion is a belief, while a hallucination is a sensory experience', 'A delusion affects memory, while a hallucination affects sleep', 'A delusion is always temporary, while a hallucination is permanent', 'There is no meaningful difference between them'], 'A delusion is a belief, while a hallucination is a sensory experience', 'Delusions are strongly held beliefs not grounded in reality. Hallucinations are sensory experiences, such as hearing a voice others do not hear.'],
    ['Which is an example of a negative symptom of schizophrenia?', ['Reduced motivation or emotional expression', 'Hearing a voice that others do not hear', 'Holding a fixed false belief', 'Speaking in a highly disorganized way'], 'Reduced motivation or emotional expression', 'Negative symptoms involve a reduction in usual functioning, such as motivation, emotional expression, speech, or social connection.'],
    ['Which statement best describes care for schizophrenia?', ['Care often combines medication, psychosocial support, and help with daily functioning', 'Medication addresses every support need on its own', 'A person should wait for a crisis before seeking care', 'Recovery support should exclude family or trusted people'], 'Care often combines medication, psychosocial support, and help with daily functioning', 'Coordinated care can combine medication, therapy, education, family support, and practical help with school, work, housing, or relationships.'],
  ],
  eating: [
    ['Why are eating disorders considered serious mental health conditions?', ['They can harm physical health, emotional well-being, and daily functioning', 'They are defined only by a person\'s body size', 'They reflect a simple preference about food', 'They affect only people who visibly lose weight'], 'They can harm physical health, emotional well-being, and daily functioning', 'Eating disorders can have serious medical and psychological effects at any body size and deserve timely, compassionate care.'],
    ['What distinguishes binge-eating disorder from bulimia nervosa?', ['Bulimia includes repeated compensatory behaviors after binge eating', 'Binge-eating disorder never involves distress or loss of control', 'Bulimia is defined only by eating less than usual', 'The two conditions always have identical symptoms'], 'Bulimia includes repeated compensatory behaviors after binge eating', 'Both can involve binge eating and loss of control. Bulimia also includes recurring compensatory behaviors such as vomiting, fasting, or excessive exercise.'],
    ['Why can eating-disorder care involve several kinds of professionals?', ['Treatment may need to address medical health, nutrition, thoughts, and behavior together', 'No single professional can recognize an eating disorder', 'Every person needs the same number of clinicians', 'The condition is mainly a problem of food education'], 'Treatment may need to address medical health, nutrition, thoughts, and behavior together', 'A coordinated team can support physical safety, nutrition, emotions, relationships, and behavior based on the person\'s needs.'],
    ['Which statement about who can have an eating disorder is accurate?', ['People of any body size, gender, age, or background can be affected', 'Only people who are underweight can be affected', 'Only adolescents can be affected', 'Appearance reliably shows whether someone is affected'], 'People of any body size, gender, age, or background can be affected', 'Eating disorders occur across body sizes and backgrounds. Appearance alone cannot show whether someone needs support.'],
  ],
  odd: [
    ['What helps distinguish ODD from ordinary oppositional behavior in childhood?', ['The pattern is frequent, ongoing, and causes significant problems', 'A child disagrees with an adult once', 'The behavior occurs only when a child is tired', 'A child prefers making their own choices'], 'The pattern is frequent, ongoing, and causes significant problems', 'ODD involves a persistent pattern that affects relationships, school, home life, or other important settings. A single disagreement is not enough.'],
    ['Which statement best reflects what is known about the causes of ODD?', ['Several developmental, biological, family, and environmental factors may interact', 'One parenting decision directly causes the disorder', 'The condition is caused by a child choosing to misbehave', 'A child\'s temperament determines the outcome by itself'], 'Several developmental, biological, family, and environmental factors may interact', 'ODD is complex and does not have one known cause. Assessment should consider the child and the broader context without assigning blame.'],
    ['What is a common focus of support for ODD?', ['Building consistent, positive strategies across caregivers and settings', 'Responding to every conflict with punishment', 'Avoiding communication about difficult behavior', 'Expecting the child to manage the pattern alone'], 'Building consistent, positive strategies across caregivers and settings', 'Support often helps caregivers and children build communication, predictable expectations, problem-solving, and emotional regulation skills.'],
    ['Why does diagnosing ODD require a qualified professional?', ['They assess persistence, severity, development, setting, and other possible conditions', 'A short online quiz can confirm the diagnosis first', 'Every disagreement with authority has the same meaning', 'Diagnosis depends only on behavior reported at school'], 'They assess persistence, severity, development, setting, and other possible conditions', 'A careful evaluation considers development, context, duration, impairment, and conditions that can look similar or occur alongside ODD.'],
  ],
  neuro: [
    ['Which statement best describes neurodevelopmental disorders?', ['They begin during development and can affect learning, attention, communication, movement, or social skills', 'They begin only after age 50', 'They affect every person in the same way', 'They are temporary reactions to stress'], 'They begin during development and can affect learning, attention, communication, movement, or social skills', 'Neurodevelopmental disorders are a broad group that begins during development. Their effects and support needs vary widely.'],
    ['Which group contains examples of neurodevelopmental disorders?', ['ADHD, autism spectrum disorder, and intellectual developmental disorders', 'PTSD, panic disorder, and major depression', 'Bipolar disorder, schizophrenia, and bulimia nervosa', 'Insomnia, migraine, and seasonal allergies'], 'ADHD, autism spectrum disorder, and intellectual developmental disorders', 'ADHD, autism spectrum disorder, and intellectual developmental disorders are among the conditions included in this broad category.'],
    ['Why should support for a neurodevelopmental condition be individualized?', ['People have different strengths, environments, goals, and support needs', 'The same diagnosis always produces the same experience', 'Support is useful only during early childhood', 'Accommodations are intended to lower expectations'], 'People have different strengths, environments, goals, and support needs', 'Individualized support responds to the person\'s strengths, needs, environment, communication, and goals across life stages.'],
    ['What is the purpose of an educational accommodation?', ['It improves access to learning without changing a person\'s worth or potential', 'It guarantees that learning will never be difficult', 'It replaces all teaching and skill development', 'It confirms a diagnosis without an evaluation'], 'It improves access to learning without changing a person\'s worth or potential', 'Accommodations reduce barriers and help a person access learning. They are not a judgment about intelligence, effort, or potential.'],
  ],
}
