# Generated by ChatGPT on 2026-06-24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_journal_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('initial', 'Initial'), ('weekly', 'Weekly')], max_length=20)),
                ('question_ids', models.JSONField(blank=True, default=list)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('check_in_date', models.DateField(default=django.utils.timezone.localdate)),
                ('week_start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['check_in_date', 'created_at', 'id'],
                'indexes': [
                    models.Index(fields=['user', 'type', 'check_in_date'], name='app_checkin_user_id_907872_idx'),
                    models.Index(fields=['user', 'week_start_date'], name='app_checkin_user_id_9de0b5_idx'),
                ],
            },
        ),
    ]
