# Generated by ChatGPT on 2026-06-24

import django.db.models.constraints
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughtjournalentry',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddIndex(
            model_name='thoughtjournalentry',
            index=models.Index(fields=['user', 'entry_date'], name='app_thoughtj_user_id_6156e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='thoughtjournalentry',
            constraint=django.db.models.constraints.UniqueConstraint(fields=('user', 'entry_date'), name='unique_journal_entry_per_user_date'),
        ),
    ]
