# Generated by Django 6.0.6 on 2026-06-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_thoughtjournalentry_entry_date'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='checkin',
            new_name='app_checkin_user_id_d57ca7_idx',
            old_name='app_checkin_user_id_907872_idx',
        ),
        migrations.RenameIndex(
            model_name='checkin',
            new_name='app_checkin_user_id_568175_idx',
            old_name='app_checkin_user_id_9de0b5_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='app_convers_user_id_932436_idx',
            old_name='app_convers_user_id_ee57d8_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='app_convers_created_85cae7_idx',
            old_name='app_convers_created_408413_idx',
        ),
        migrations.RenameIndex(
            model_name='journaldoodle',
            new_name='app_journal_user_id_371920_idx',
            old_name='app_journa_user_id_e8de0b_idx',
        ),
        migrations.RenameIndex(
            model_name='journaldoodle',
            new_name='app_journal_entry_i_c587c1_idx',
            old_name='app_journa_entry_i_36d360_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='app_message_convers_a90755_idx',
            old_name='app_messag_convers_719fb2_idx',
        ),
        migrations.RenameIndex(
            model_name='thoughtjournalentry',
            new_name='app_thought_user_id_26a347_idx',
            old_name='app_thoughtj_user_id_6156e7_idx',
        ),
        migrations.RenameIndex(
            model_name='thoughtjournalentry',
            new_name='app_thought_user_id_bf5498_idx',
            old_name='app_thoughtj_user_id_46b595_idx',
        ),
    ]
