# Generated by ChatGPT on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_thoughtjournalentry_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughtjournalentry',
            name='mood',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
