# Generated by Django 6.0.6 on 2026-06-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_app_checkin_user_id_907872_idx_app_checkin_user_id_d57ca7_idx_and_more'),
        ('app', '0006_thoughtjournalentry_mood'),
    ]

    operations = [
    ]
