# Generated by Django 6.0.6 on 2026-06-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_therapistmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='therapist_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='app.therapistmatch'),
        ),
    ]
