# Generated by Django 6.0.8 on 2026-09-20 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ROOM_CATEGORIES = (
    ('anxiety', 'Anxiety', 'A supportive space for managing worry, fear, and anxious thoughts.'),
    ('loneliness', 'Loneliness', 'A supportive space for connection, belonging, and feeling less alone.'),
    ('grief', 'Grief', 'A supportive space for living with loss, change, and remembrance.'),
    ('burnout', 'Burnout', 'A supportive space for exhaustion, boundaries, and sustainable recovery.'),
    ('stress', 'Stress', 'A supportive space for daily pressure, overwhelm, and steadier coping.'),
    ('confidence', 'Low Confidence', 'A supportive space for self-trust, confidence, and personal growth.'),
)


def seed_peer_rooms_and_place_existing_users(apps, schema_editor):
    CheckIn = apps.get_model('app', 'CheckIn')
    PeerRoom = apps.get_model('app', 'PeerRoom')
    PeerRoomMembership = apps.get_model('app', 'PeerRoomMembership')
    PeerRoomWaitlist = apps.get_model('app', 'PeerRoomWaitlist')
    UserProfile = apps.get_model('app', 'UserProfile')

    PeerRoom.objects.filter(is_active=True).update(is_active=False)

    rooms_by_category = {}
    for category, label, description in ROOM_CATEGORIES:
        rooms = []
        for slot in (1, 2):
            rooms.append(PeerRoom.objects.create(
                name=f'{label} Support Room {slot}',
                topic=category,
                slot=slot,
                capacity=20,
                description=description,
                is_active=True,
            ))
        rooms_by_category[category] = rooms

    category_order = [category for category, _, _ in ROOM_CATEGORIES]
    occupancy = {room.id: 0 for rooms in rooms_by_category.values() for room in rooms}

    for profile in UserProfile.objects.order_by('created_at', 'id').iterator():
        initial = (
            CheckIn.objects
            .filter(user_id=profile.user_id, type='initial')
            .order_by('created_at', 'id')
            .first()
        )
        scores = initial.scores if initial and isinstance(initial.scores, dict) else {}
        valid_scores = {
            category: value
            for category, value in scores.items()
            if category in category_order and isinstance(value, (int, float))
        }
        if not valid_scores:
            continue

        highest = max(valid_scores.values())
        category = next(
            item for item in category_order if valid_scores.get(item) == highest
        )
        UserProfile.objects.filter(pk=profile.pk).update(peer_support_category=category)

        if not profile.is_peer_onboarded:
            continue

        available_rooms = [
            room for room in rooms_by_category[category] if occupancy[room.id] < room.capacity
        ]
        if available_rooms:
            room = min(available_rooms, key=lambda candidate: (occupancy[candidate.id], candidate.slot))
            PeerRoomMembership.objects.create(
                user_id=profile.user_id,
                room_id=room.id,
                category=category,
                status='active',
            )
            occupancy[room.id] += 1
        else:
            PeerRoomWaitlist.objects.create(
                user_id=profile.user_id,
                category=category,
                reason='capacity',
                minimum_room_slot=1,
                status='waiting',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userprofile_avatar_symbols'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerRoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('anxiety', 'Anxiety'), ('loneliness', 'Loneliness'), ('grief', 'Grief'), ('burnout', 'Burnout'), ('stress', 'Stress'), ('confidence', 'Low confidence')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=12)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('switched', 'Switched rooms'), ('opted_out', 'Opted out'), ('room_closed', 'Room closed')], default='', max_length=20)),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PeerRoomWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('anxiety', 'Anxiety'), ('loneliness', 'Loneliness'), ('grief', 'Grief'), ('burnout', 'Burnout'), ('stress', 'Stress'), ('confidence', 'Low confidence')], max_length=20)),
                ('reason', models.CharField(choices=[('capacity', 'Rooms full'), ('opted_out', 'Waiting for a future room')], default='capacity', max_length=16)),
                ('minimum_room_slot', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('assigned', 'Assigned'), ('cancelled', 'Cancelled')], default='waiting', max_length=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='peerroom',
            options={'ordering': ['topic', 'slot', 'id']},
        ),
        migrations.AddField(
            model_name='peerroom',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='peerroom',
            name='slot',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='peer_support_category',
            field=models.CharField(blank=True, choices=[('anxiety', 'Anxiety'), ('loneliness', 'Loneliness'), ('grief', 'Grief'), ('burnout', 'Burnout'), ('stress', 'Stress'), ('confidence', 'Low confidence')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='peerroom',
            name='topic',
            field=models.CharField(choices=[('anxiety', 'Anxiety'), ('loneliness', 'Loneliness'), ('grief', 'Grief'), ('burnout', 'Burnout'), ('stress', 'Stress'), ('confidence', 'Low confidence')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='peerroom',
            constraint=models.CheckConstraint(condition=models.Q(('slot__gte', 1)), name='peer_room_slot_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='peerroom',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='peer_room_capacity_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='peerroom',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('topic', 'slot'), name='unique_active_peer_room_topic_slot'),
        ),
        migrations.AddField(
            model_name='peerroommembership',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app.peerroom'),
        ),
        migrations.AddField(
            model_name='peerroommembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_room_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peerroomwaitlist',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_waitlist_entries', to='app.peerroom'),
        ),
        migrations.AddField(
            model_name='peerroomwaitlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_room_waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='peerroommembership',
            index=models.Index(fields=['room', 'status'], name='app_peerroo_room_id_e4d935_idx'),
        ),
        migrations.AddIndex(
            model_name='peerroommembership',
            index=models.Index(fields=['category', 'status'], name='app_peerroo_categor_dcc006_idx'),
        ),
        migrations.AddConstraint(
            model_name='peerroommembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='unique_active_peer_room_membership'),
        ),
        migrations.AddIndex(
            model_name='peerroomwaitlist',
            index=models.Index(fields=['category', 'status', 'joined_at'], name='app_peerroo_categor_81336b_idx'),
        ),
        migrations.AddConstraint(
            model_name='peerroomwaitlist',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_room_slot__gte', 1)), name='peer_waitlist_min_slot_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='peerroomwaitlist',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'waiting')), fields=('user',), name='unique_waiting_peer_room_entry'),
        ),
        migrations.RunPython(seed_peer_rooms_and_place_existing_users, migrations.RunPython.noop),
    ]
